#!/usr/bin/env swift

import Foundation
import Cocoa

// 実装コードを直接インポートできないので、同等の構造を再定義
// 実際のアプリでは LaserGuide モジュールをインポート

print("=== LaserGuide v2 データモデル完全動作確認 ===\n")

// このスクリプトでは、実際のアプリコードを使った確認が必要
print("【注意】")
print("このテストは実際のアプリコードを使用する必要があります。")
print("以下の手順で確認してください：\n")

print("1. Xcodeプロジェクトに新規ファイルを追加")
print("2. テストターゲットを作成")
print("3. 以下のテストコードを実行\n")

print("```swift")
print("import XCTest")
print("@testable import LaserGuide")
print("")
print("class DataModelWorkflowTests: XCTestCase {")
print("    func testCompleteWorkflow() throws {")
print("        // === Phase 1: サンプル設定作成 ===")
print("        print(\"\\n=== Phase 1: サンプル設定作成 ===\\n\")")
print("        ")
print("        let screens = NSScreen.screens")
print("        var workspace = WorkspaceConfiguration.createDefault(screens: screens)")
print("        ")
print("        // サンプルPassSegmentを設定（LG右下→内蔵右上ワープ）")
print("        let builtin = workspace.displays[0]")
print("        let lg = workspace.displays[1]")
print("        ")
print("        // 内蔵 top PassSegments")
print("        let builtinTopSeg1 = PassSegment(")
print("            displayId: builtin.id,")
print("            side: .top,")
print("            logical: SegmentRange(start: 0.0, end: 3440.0),")
print("            physical: SegmentRange(start: 0.0, end: 342.6)")
print("        )")
print("        ")
print("        let builtinTopSeg2 = PassSegment(")
print("            displayId: builtin.id,")
print("            side: .top,")
print("            logical: SegmentRange(start: 3456.0, end: 3456.0),  // 空セグメント")
print("            physical: SegmentRange(start: 344.2, end: 344.2)")
print("        )")
print("        ")
print("        // LG bottom PassSegments")
print("        let lgBottomSeg1 = PassSegment(")
print("            displayId: lg.id,")
print("            side: .bottom,")
print("            logical: SegmentRange(start: 0.0, end: 1125.0),")
print("            physical: SegmentRange(start: 0.0, end: 344.2)")
print("        )")
print("        ")
print("        let lgBottomSeg2 = PassSegment(")
print("            displayId: lg.id,")
print("            side: .bottom,")
print("            logical: SegmentRange(start: 1125.0, end: 3440.0),")
print("            physical: SegmentRange(start: 344.2, end: 1052.7)")
print("        )")
print("        ")
print("        // Display設定")
print("        builtinTopSeg1.display = builtin")
print("        builtinTopSeg2.display = builtin")
print("        lgBottomSeg1.display = lg")
print("        lgBottomSeg2.display = lg")
print("        ")
print("        // ペアリング設定（相互）")
print("        builtinTopSeg1.pairedSegment = lgBottomSeg1")
print("        lgBottomSeg1.pairedSegment = builtinTopSeg1")
print("        builtinTopSeg2.pairedSegment = lgBottomSeg2")
print("        lgBottomSeg2.pairedSegment = builtinTopSeg2")
print("        ")
print("        // Displayに追加")
print("        workspace.displays[0].passSegments = [builtinTopSeg1, builtinTopSeg2]")
print("        workspace.displays[1].passSegments = [lgBottomSeg1, lgBottomSeg2]")
print("        ")
print("        // === Phase 2: ダンプ（保存前）===")
print("        print(\"\\n=== Phase 2: ダンプ（保存前）===\\n\")")
print("        ")
print("        let encoder = JSONEncoder()")
print("        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]")
print("        encoder.dateEncodingStrategy = .iso8601")
print("        ")
print("        // Workspace JSON")
print("        let workspaceJSON = try encoder.encode(workspace)")
print("        print(\"【WorkspaceConfiguration JSON】\")")
print("        print(String(data: workspaceJSON, encoding: .utf8)!)")
print("        ")
print("        // AppConfiguration作成")
print("        let appConfig = AppConfiguration(")
print("            workspaceKey: workspace.configurationKey,")
print("            laser: AppConfiguration.LaserConfiguration(),")
print("            edgeNavigation: AppConfiguration.EdgeNavigationConfiguration()")
print("        )")
print("        appConfig.workspace = workspace")
print("        ")
print("        // AppConfiguration JSON")
print("        let appConfigJSON = try encoder.encode(appConfig)")
print("        print(\"\\n【AppConfiguration JSON（保存用）】\")")
print("        print(String(data: appConfigJSON, encoding: .utf8)!)")
print("        ")
print("        // === Phase 3: 保存 ===")
print("        print(\"\\n=== Phase 3: 保存 ===\\n\")")
print("        ")
print("        ConfigurationManager.shared.saveWorkspace(workspace)")
print("        AppConfigurationManager.shared.saveConfiguration(appConfig)")
print("        ")
print("        print(\"✅ 保存完了\")")
print("        ")
print("        // === Phase 4: ロード ===")
print("        print(\"\\n=== Phase 4: ロード ===\\n\")")
print("        ")
print("        let loadedAppConfig = AppConfigurationManager.shared.loadConfiguration()")
print("        let loadedWorkspace = ConfigurationManager.shared.loadWorkspace(for: loadedAppConfig!.workspaceKey)")
print("        ")
print("        // === Phase 5: ダンプ（復元後）===")
print("        print(\"\\n=== Phase 5: ダンプ（復元後）===\\n\")")
print("        ")
print("        let loadedWorkspaceJSON = try encoder.encode(loadedWorkspace!)")
print("        print(\"【復元されたWorkspaceConfiguration】\")")
print("        print(String(data: loadedWorkspaceJSON, encoding: .utf8)!)")
print("        ")
print("        let loadedAppConfigJSON = try encoder.encode(loadedAppConfig!)")
print("        print(\"\\n【復元されたAppConfiguration】\")")
print("        print(String(data: loadedAppConfigJSON, encoding: .utf8)!)")
print("        ")
print("        // === Phase 6: 比較 ===")
print("        print(\"\\n=== Phase 6: 比較 ===\\n\")")
print("        ")
print("        print(\"元のworkspaceKey: \\(workspace.configurationKey)\")")
print("        print(\"復元後workspaceKey: \\(loadedWorkspace!.configurationKey)\")")
print("        print(\"一致: \\(workspace.configurationKey == loadedWorkspace!.configurationKey)\")")
print("        ")
print("        print(\"\\n元のPassSegment数: \\(workspace.displays.flatMap { $0.passSegments }.count)\")")
print("        print(\"復元後PassSegment数: \\(loadedWorkspace!.displays.flatMap { $0.passSegments }.count)\")")
print("        ")
print("        // pairedSegmentキャッシュ確認")
print("        let firstSegment = loadedWorkspace!.displays[0].passSegments[0]")
print("        print(\"\\npairedSegmentキャッシュ: \\(firstSegment.pairedSegment != nil ? \"設定済み\" : \"nil\")\")")
print("        print(\"pairedDisplayName: \\(firstSegment.pairedDisplayName ?? \"nil\")\")")
print("    }")
print("}")
print("```")
print("")
print("このテストを実行して、以下を確認：")
print("1. 保存前後でデータが一致")
print("2. pairedSegmentキャッシュが自動設定")
print("3. デバッグヒントが正しく保存・復元")
print("4. workspace参照が正しく動作")

